### PR TITLE
Implement URL slugs

### PR DESCRIPTION
**Pull request by EmilFattakhov**
This PR:

- Implements URL slugs
- Sets up redirects for all old variations of the page to the newly updated route (slug)
- Sorts the redirects according to the navigation indexer inside the config file for ease of review and ease of maintenance 
- Adjusts the top navbar links to work with the updated slugs, drops some outdated information, links the updated website

I very carefully worked on setting up the redirect so hopefully all the links that have been posted or linked anywhere before should continue working. Any suggestions on the slugs implementation and naming are welcome!

### CODE REVIEW

**Comment by EmilFattakhov** [comment]
> Do slugs support paths? Something about slugs like `/auto-consensus` conveys no context that this link takes you to a page about developing on Autonomys using our SDK. Maybe I'm old-fashioned about they way I look at URLs.

I was also thinking about that, but the more specific we will try to be, the longer the URL become :) 
Yes, the paths are supported, we can generalize them into `/docs/farming`, `/docs/staking`, `/docs/develop`, `/docs/community`, or the same paths but without the `/docs` part if I'm able to find where this is coming from :)

**Comment by EmilFattakhov** [comment]
> Are we keeping the root /docs/ path? Is there the possibility to ditch it? It makes sense to do this job just once.

We should be able to, investigating where it's coming from

**Comment by jim-counter** [comment]
> We should be able to, investigating where it's coming from

Part of the deploy config?

**Comment by jim-counter** [comment]
> we can generalize them into `/docs/farming`, `/docs/staking`, `/docs/develop`, `/docs/community`, or the same paths but without the `/docs` part if I'm able to find where this is coming from :)

I like this idea.

**Review by randywessels — APPROVED** [review]
To be honest, I don't know a whole log about slugs.  Most of your code changes were adding slugs to they look straight-forward.  The redirects section was a bit more confusing, but I did go to every page and the links all seem to work.  The url's after the domain name are smaller, so I believe it is working as intended.  The only odd thing that I saw is also a problem in the current version.  That is when you expand too many things on the left, at a point slightly taller than your page height the menu links get cut off.

**Comment by EmilFattakhov** [comment]
Closed with the merge of https://github.com/autonomys/subspace-docs/pull/677

**Pull request closed without merging**
