### PR TITLE
Refresh community tools

### PR DESCRIPTION
**Pull request by vexr**
- Updated the community built tools section and removed  iframes.

- Added another site to the community tools collection (run by me).

### CODE REVIEW

**Comment by jim-counter** [comment]
@EmilFattakhov can you check the missing `CROWDIN_PERSONAL_TOKEN` deploy error please,

**Review by EmilFattakhov — COMMENTED** [review]
Is there any specific reason you believe we should remove the Iframe for the community tools @vexr? I personally don't like iFrames, but in this case, it was beneficial for the users to scroll through the available 3-rd party tools without having to go to another website

**Comment by vexr** [comment]
Beyond aesthetics, using iframes introduces functional limitations. For example, GitHub blocks access when embedded in an iframe, so any links to GitHub will fail to load if they're not set to open in a new tab. This disrupts the user experience for accessing GitHub repos for these tools.

This can be seen when trying to access the GitHub link on the first tool 'Farm Monitoring script — Windows/Linux/OSX]' from within the iframe.

**Review by EmilFattakhov — APPROVED** [review]
I see, yeah that's slightly annoying. Okay, let's give this a try, thanks vexr!

**Pull request merged**
